version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.3.0
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=elasticsearch #集群名称为elasticsearch
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" #jvm内存分配为1024MB
      # - "discovery.type=single-node" #单节点启动
      - "TZ=Asia/Shanghai"
    volumes:
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
      - /data/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
  elasticsearch-data1:
    image: elasticsearch:7.3.0
    container_name: elasticsearch-data1
    restart: always
    environment:
      - cluster.name=elasticsearch #集群名称为elasticsearch
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" #jvm内存分配为1024MB
      # - "discovery.type=single-node" #单节点启动
      - "TZ=Asia/Shanghai"
    volumes:
      - /data/elasticsearch-data1/data:/usr/share/elasticsearch/data
      - /data/elasticsearch-data1/logs:/usr/share/elasticsearch/logs
      - /data/elasticsearch-data1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9200
      - 9301:9300
  elasticsearch-data2:
    image: elasticsearch:7.3.0
    container_name: elasticsearch-data2
    restart: always
    environment:
      - cluster.name=elasticsearch #集群名称为elasticsearch
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" #jvm内存分配为1024MB
      # - "discovery.type=single-node" #单节点启动
      - "TZ=Asia/Shanghai"
    volumes:
      - /data/elasticsearch-data2/data:/usr/share/elasticsearch/data
      - /data/elasticsearch-data2/logs:/usr/share/elasticsearch/logs
      - /data/elasticsearch-data2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9202:9200
      - 9302:9300
  kibana:
    image: kibana:7.3.0
    container_name: kibana
    restart: always
    links:
      - elasticsearch:es #配置elasticsearch域名为es
      - elasticsearch-data1:es-d1
      - elasticsearch-data2:es-d2
    depends_on:
      - elasticsearch
      - elasticsearch-data1
      - elasticsearch-data2
    volumes:
      - /data/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - "elasticsearch.hosts=http://es:9200" #因为上面配置了域名，所以这里可以简写为http://es:9200
    ports:
      - 5601:5601
  logstash:
    image: logstash:7.3.0
    container_name: logstash
    restart: always
    volumes:
      - /data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /data/logstash/jars/mysql-connector-java-8.0.11.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.11.jar
    depends_on:
      - elasticsearch
      - elasticsearch-data1
      - elasticsearch-data2
    links:
      - elasticsearch:es
      - elasticsearch-data1:es-d1
      - elasticsearch-data2:es-d2
    ports:
      - 4560:4560
